# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created: Fri Apr 27 14:58:33 2018
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(400, 500)
        MainWindow.setMinimumSize(QtCore.QSize(400, 500))
        MainWindow.setMaximumSize(QtCore.QSize(400, 500))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.displayLCD = QtGui.QLCDNumber(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.displayLCD.setFont(font)
        self.displayLCD.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.displayLCD.setStyleSheet(_fromUtf8(""))
        self.displayLCD.setFrameShape(QtGui.QFrame.NoFrame)
        self.displayLCD.setSmallDecimalPoint(True)
        self.displayLCD.setNumDigits(17)
        self.displayLCD.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.displayLCD.setProperty("intValue", 0)
        self.displayLCD.setObjectName(_fromUtf8("displayLCD"))
        self.verticalLayout.addWidget(self.displayLCD)
        self.numpad = QtGui.QHBoxLayout()
        self.numpad.setObjectName(_fromUtf8("numpad"))
        self.numpadL = QtGui.QVBoxLayout()
        self.numpadL.setObjectName(_fromUtf8("numpadL"))
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        self.pushButton.setMinimumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(50)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.numpadL.addWidget(self.pushButton)
        self.pushButton_2 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_2.setMinimumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(50)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.numpadL.addWidget(self.pushButton_2)
        self.pushButton_3 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_3.setMinimumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(50)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.numpadL.addWidget(self.pushButton_3)
        self.pushButton_10 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_10.setMinimumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(50)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setObjectName(_fromUtf8("pushButton_10"))
        self.numpadL.addWidget(self.pushButton_10)
        self.numpad.addLayout(self.numpadL)
        self.numpadM = QtGui.QVBoxLayout()
        self.numpadM.setObjectName(_fromUtf8("numpadM"))
        self.pushButton_5 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_5.setMinimumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(50)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.numpadM.addWidget(self.pushButton_5)
        self.pushButton_4 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_4.setMinimumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(50)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.numpadM.addWidget(self.pushButton_4)
        self.pushButton_6 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_6.setMinimumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(50)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.numpadM.addWidget(self.pushButton_6)
        self.pushButton_11 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_11.setMinimumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(50)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setObjectName(_fromUtf8("pushButton_11"))
        self.numpadM.addWidget(self.pushButton_11)
        self.numpad.addLayout(self.numpadM)
        self.numpadR = QtGui.QVBoxLayout()
        self.numpadR.setObjectName(_fromUtf8("numpadR"))
        self.pushButton_8 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_8.setMinimumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(50)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.numpadR.addWidget(self.pushButton_8)
        self.pushButton_9 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_9.setMinimumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(50)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setObjectName(_fromUtf8("pushButton_9"))
        self.numpadR.addWidget(self.pushButton_9)
        self.pushButton_7 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_7.setMinimumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(50)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.numpadR.addWidget(self.pushButton_7)
        self.pushButton_12 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_12.setMinimumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(50)
        self.pushButton_12.setFont(font)
        self.pushButton_12.setObjectName(_fromUtf8("pushButton_12"))
        self.numpadR.addWidget(self.pushButton_12)
        self.numpad.addLayout(self.numpadR)
        self.verticalLayout.addLayout(self.numpad)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Python Calculator", None))
        self.pushButton.setText(_translate("MainWindow", "9", None))
        self.pushButton_2.setText(_translate("MainWindow", "4", None))
        self.pushButton_3.setText(_translate("MainWindow", "1", None))
        self.pushButton_10.setText(_translate("MainWindow", "+/-", None))
        self.pushButton_5.setText(_translate("MainWindow", "8", None))
        self.pushButton_4.setText(_translate("MainWindow", "5", None))
        self.pushButton_6.setText(_translate("MainWindow", "2", None))
        self.pushButton_11.setText(_translate("MainWindow", "0", None))
        self.pushButton_8.setText(_translate("MainWindow", "7", None))
        self.pushButton_9.setText(_translate("MainWindow", "6", None))
        self.pushButton_7.setText(_translate("MainWindow", "3", None))
        self.pushButton_12.setText(_translate("MainWindow", ".", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

